name: flutter_monorepo_boilerplate
description: A new Flutter monorepo project.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

workspaces:
  - packages/app
  - packages/core
  - packages/shared
  - packages/features/home
